packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  prettier: ^3.5.3
  prettier-plugin-classnames: ^0.8.2
  prettier-plugin-merge: ^0.8.0
  prettier-plugin-tailwindcss: ^0.6.14
  eslint: '^9.33.0'
  typescript: ^5.8.3
  tailwindcss: ^4.1.2
  postcss: ^8.5.3
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@tailwindcss/postcss': ^4.1.2
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild
